### ISSUE TITLE
Orientation isn't persisted in background mode

### ISSUE THREAD

**Issue by jandersen** [cooperhewitt/Planetary#133]
From iTunes App Store review:

"Also, just noticed, when I pop back into Planetary from another application, it is rotated to portrait orientation even though I've kept my iPad in landscape the whole time."

**Comment by RandomEtc** [comment]
From Jürg, by email:
- rotate your ipad to landscape, put it on the table (still in landscape)
- launch planetary.app
  => the intro-screen shows in portrait!
  => the content shows in portrait!
- so you need to lift your ipad again... rotate... until you get planetary.app running in landscape
- once you have planetary.app showing in landscape:
- double-tap home button
- switch to another app (e.g. Mail.app)
- double-tap home button
- switch back to planetary.app
  => again: planetary.app shows in portrait instead of landscape!
- so you need to lift your ipad again... rotate... until you get planetary.app running in landscape

**Comment by RandomEtc** [comment]
Seems to be fixed by setting the supported orientations in the Kepler target in xcode - as dude suggested. Closing!
