### ISSUE TITLE
Atmosphere graphic depth sort

### ISSUE THREAD

**Issue by flight404** [cooperhewitt/Planetary#158]
The graphic used for the atmosphere effect is no longer participating in the fine art of depth sorting. Perhaps related to the recent changes to arcball and camera? Otherwise, no other weirdnesses noticed.

**Comment by RandomEtc** [comment]
This was happening before I made those changes (I made some screenshots just before I worked on the arcball). Thanks for noting it here!

Now I've changed the arcball we'll need to sort by distance-from-camera rather than world.z. Shouldn't be a major change but it might be a bit slower so we'll have to watch it. (Getting rid of the mTransPos and mMatrix math should help).

**Comment by RandomEtc** [comment]
Pretty sure this is fixed now (pushed in 15b4fc8649bd66f21a33f76d6806c6ae9032f45d). Let's re-open this issue if it comes back.
