### ISSUE TITLE
Scrubbable playhead should be smooth

### ISSUE THREAD

**Issue by flight404** [cooperhewitt/Planetary#72]
Might be worthwhile to make the player pause when you drag the playhead and then have it start back up at the appropriate time when the playhead is released.

**Comment by RandomEtc** [comment]
Agreed. Or a delay before the seek is applied for real. Would need to change how we drive the playhead, since right now we're reading the elapsed time from the track... we might introduce syncing issues or loops if we're not careful.

**Comment by flight404** [comment]
Increased the hitsize for the slider. much easier to grab ahold of now.

**Comment by RandomEtc** [comment]
I think I figured this one out. The slow thing, that we used to do per frame, was `mIpodPlayer.getPlayingTrack()->getLength()` ... now we're carefully caching that the playhead slider seems snappy. I added some checks so that we pretend the playhead progress is the elapsed time, while we're dragging, and that makes it so you can scrub around the orbit at full speed. Will post demo shortly!

(Needs a couple of extra checks for what to do at the end of the track, but it's pretty solid)
